---
sudo: required
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip3 install molecule docker
script:
  - molecule test
