---
# tasks file for unzip - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Installing {{ unzip_app }}
  ansible.builtin.apt:
    name: "{{ unzip_app }}"
    state: "{{ unzip_desired_state }}"
    force_apt_get: yes
    update_cache: yes
