---
# tasks file for unzip - Ubuntu

- name: "Installing {{ unzip_app }} on Debian based systems."
  apt:
    name: "{{ unzip_app }}"
    state: "{{ unzip_desired_state }}"
    force_apt_get: yes
    update_cache: yes
